apiVersion: v1
kind: Service
metadata:
  name: selenium-standalone-firefox
  namespace: selenium
  labels:
    app: selenium-standalone-firefox
spec:
  ports:
  - port: 4444
  selector:
    app: selenium-standalone-firefox